# Generated by Django 6.0.6 on 2026-06-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
